In [53]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

In [54]:
print(torch.__version__)

2.0.1


# 1. creating tensor

In [55]:
# scalar
scalar = torch.tensor(7)
vector = torch.tensor([7,8])
matrix1 = torch.tensor([[1,2],[3,4]])

print(scalar)
print(vector)
print(matrix1)
print(matrix1[0])

tensor(7)
tensor([7, 8])
tensor([[1, 2],
        [3, 4]])
tensor([1, 2])


In [56]:
print("dimension of scalar =", scalar.ndim)
print("dimension of vector =", vector.ndim)
print("dimension of matrix1 =", matrix1.ndim)

dimension of scalar = 0
dimension of vector = 1
dimension of matrix1 = 2


In [5]:
print(scalar.item())
try :
    print(vector.iem())
except :
    print("a Tensor with 2 elements cannot be converted to Scalar")

7
a Tensor with 2 elements cannot be converted to Scalar


In [6]:
TENSOR = torch.tensor([[[1,2,3]
                        ,[4,5,6]
                        ,[7,8,9]]])

print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


# 2. Random tensor

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [62]:
random_tensor = torch.rand(size = (3,4))


In [65]:
print(random_tensor)
print()
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

torch.Size([3, 4])
2


In [66]:
random_image_size_tensor = torch.rand(size=(3,224,224))  # height, width, color chanels
#print(random_image_size_tensor)


In [67]:
print("dim of random_image_size_tensor =", random_image_size_tensor.ndim)
print("shape of random_image_size_tensor =", random_image_size_tensor.shape)

dim of random_image_size_tensor = 3
shape of random_image_size_tensor = torch.Size([3, 224, 224])


# 3. zero and one tensor

In [68]:
zero_torch = torch.zeros(size = (3,4))
print(zero_torch)
print(zero_torch.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [69]:
one_tensor = torch.ones(size = (2,2))
print(one_tensor)

print(one_tensor.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


# 4. create a range of tensor

In [70]:
# use torch.range()
#
torch_x1 = torch.range(0,10)
torch_x2 = torch.arange(0,10)
torch_y = torch.arange(0,10,2)

torch_z = torch_y

/var/folders/gx/tf0br2xj25g43r5nz32nklmh0000gn/T/ipykernel_23648/3983776290.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch_x1 = torch.range(0,10)


In [71]:
print(torch_x1)
print(torch_x2)
print(torch_y)
print(torch_z)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([0, 2, 4, 6, 8])


# 5. tensor data type

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [72]:
float32_tensor = torch.tensor([3.0,6.0,9.0])
float32_tensor.dtype

torch.float32

In [73]:
float16_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16, device=None)
print(float16_tensor.dtype)
print(float16_tensor.device)            # default is none
print(float16_tensor.requires_grad)     # default is False  # if True, operations performed on the tensor are recorded

torch.float16
cpu
False


In [17]:
print(float16_tensor * float32_tensor)
print((float16_tensor * float32_tensor).dtype)

tensor([ 9., 36., 81.])
torch.float32


In [18]:
print(float16_tensor + float32_tensor)
print((float16_tensor + float32_tensor).dtype)

tensor([ 6., 12., 18.])
torch.float32


# 6. tensor operation

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication

In [74]:
tensor = torch.tensor([1,2,3])
tensor += 10
tensor

tensor([11, 12, 13])

In [75]:
tensor = torch.tensor([1,2,3])
tensor *= 10
tensor

tensor([10, 20, 30])

In [76]:
tensor = torch.tensor([1,2,3])
tensor -= 10
tensor

tensor([-9, -8, -7])

In [77]:
tensor = torch.tensor([1,2,3])
tensor = tensor/10
tensor

tensor([0.1000, 0.2000, 0.3000])

In [78]:
#vector dot product

vector = torch.tensor([1,2,3])
print(torch.matmul(vector,vector))

tensor(14)


In [79]:
# matrix multiplication

vector = torch.tensor([1,2,3])
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(vector)
print(matrix)
print(vector * matrix)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]])


In [80]:
matrix_A = torch.tensor([[7,8,9],[10,11,12]])
print(matrix_A.T)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


# 7. finding mean max sum etc.

In [81]:
x = torch.arange(0,100,10)
print(torch.min(x))

tensor(0)


In [82]:
#torch.mean(x)

# if you run this code
'''
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
 in 
----> 1 torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
'''

'\n---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\n in \n----> 1 torch.mean(x)\n\nRuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long\n'

In [84]:
x.dtype
#torch.int64 is Long which has no function .mean

torch.int64

In [85]:
# Long to float32
y = x.type(torch.float32)
print(torch.mean(y))

tensor(45.)


# 8. finding position min max

In [86]:
print(x)
print(x.argmin())
print(x.argmax())
print()
print(x[0])
print(x[9])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(9)

tensor(0)
tensor(90)


# 9. reshaping stacking squeezing and unsqueezing tensor

In [31]:
# reshape
x = torch.arange(0,12,2)
print(x,x.shape)
print()

x_reshaped = x.reshape(2,3)
print(x_reshaped,x_reshaped.shape)

tensor([ 0,  2,  4,  6,  8, 10]) torch.Size([6])

tensor([[ 0,  2,  4],
        [ 6,  8, 10]]) torch.Size([2, 3])


In [87]:
print(x)
print()

x_stacked1 = torch.stack([x,x,x,x], dim=0)
print(x_stacked1)
print()

x_stacked2 = torch.stack([x,x,x,x], dim=1)
print(x_stacked2)


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])


In [88]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.vstack((a,b)))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [89]:
x = torch.zeros(2, 1, 2, 1, 2)
print("x.size() is", x.size())
y = torch.squeeze(x)
print("y.size() is ",y.size()) 
print()



y = torch.squeeze(x, 0)
print("y.size() is ",y.size()) 
y = torch.squeeze(x, 1)
print("y.size() is ",y.size()) 
y = torch.squeeze(x, (1, 2, 3))
print("y.size() is ",y.size()) 


x.size() is torch.Size([2, 1, 2, 1, 2])
y.size() is  torch.Size([2, 2, 2])

y.size() is  torch.Size([2, 1, 2, 1, 2])
y.size() is  torch.Size([2, 2, 1, 2])
y.size() is  torch.Size([2, 2, 2])


# 10. indexing, selecting data

In [90]:
x = torch.arange(1,10).reshape(1,3,3)
print(x)
print()

print(x[0])
print()

print(x[0][0])
print()

print(x[:,0])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([1, 2, 3])

tensor([[1, 2, 3]])


In [91]:
print(x[:, :, 1])
print(x[0, 0, :])
print(x[:, :, 2])

tensor([[2, 5, 8]])
tensor([1, 2, 3])
tensor([[3, 6, 9]])


# 11. pytorch tensor and numpy

In [92]:
array = np.arange(0,10)
tensor = torch.from_numpy(array)

print(array, array.dtype)
print(tensor, tensor.dtype)


[0 1 2 3 4 5 6 7 8 9] int64
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.int64


In [93]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor)
print()

print(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])

[1. 1. 1. 1. 1. 1. 1.]


# 12. reproducibility

In [94]:
x = torch.rand(size=(3,3))
print(x)

tensor([[0.1336, 0.9666, 0.9754],
        [0.8474, 0.8988, 0.1105],
        [0.4563, 0.9719, 0.3968]])


In [95]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1496, 0.4743, 0.9973, 0.4436],
        [0.9726, 0.5194, 0.5337, 0.7050],
        [0.3362, 0.7891, 0.1694, 0.1800]])

Tensor B:
tensor([[0.7177, 0.6988, 0.5510, 0.2485],
        [0.8518, 0.0963, 0.1338, 0.2741],
        [0.6142, 0.8973, 0.3629, 0.1748]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [96]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# 13. GPU on mac (cuda is not available so using "mps" instead)

you need to install first
https://sebastianraschka.com/blog/2022/pytorch-m1-gpu.html



In [97]:
torch.cuda.is_available()

False

In [98]:
torch.has_mps

True

In [99]:
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.has_mps else 'cpu')

In [100]:
device

device(type='mps')

In [101]:
float16_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16, device='mps')
print(float16_tensor.dtype)
print(float16_tensor.device)            # default is none
print(float16_tensor.requires_grad)     # default is False  # if True, operations performed on the tensor are recorded

torch.float16
mps:0
False


# 14. putting tensors and models to gpu (only for mac) mps not cuda

In [47]:
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.has_mps else 'cpu')
print(device)

mps


In [48]:
# create a tensor (default is on cpu)

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [49]:
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [50]:
tensor2 = torch.tensor([1,2,3,4])

print(tensor2, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [51]:
tensor_on_gpu2 = tensor2.to(device)
print(tensor_on_gpu2, tensor_on_gpu2.device)

tensor([1, 2, 3, 4], device='mps:0') mps:0


# 15. moving tensor back to cpu

In [52]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

tensor([1, 2, 3]) cpu
